### ISSUE TITLE
Getting "var output to native function" error

### ISSUE THREAD

**Issue by pluckyporcupine** [meircif/lumi-lang#190]
**Describe the bug**
I have this code: `native func window-should-close()->(var Bool ret) "WindowShouldClose"`

I am getting this error: `Code error in test.5.lm[13] var output to native function`

**To Reproduce**
Try to bind the `WindowShouldClose()` function from raylib and compile the result.

**Expected behavior**
The function to be bound properly, as similar functions are in the `zlib` module and the Read the Docs examples.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Mingw64

**Comment by pluckyporcupine** [comment]
I managed to solve this by making it a `copy` instead of a `var`, but I'm unclear on the difference in this case, given the examples.

**Comment by meircif** [comment]
Currently native function return value should be `copy` and not `var` for primitives.
This is really missing from the documentation, and the `zlib` module is also broken.

**Comment by pluckyporcupine** [comment]
That might work better. At the very least, I think that eschewing the access modifier would help a bit with clarity and it would be backwards compatible going forward, as well.
