### ISSUE TITLE
How do I get Lumi to properly initialize native structs?

### ISSUE THREAD

**Issue by pluckyporcupine** [meircif/lumi-lang#191]
I have this code, which compiles: https://gist.github.com/pluckyporcupine/27db1279431807405f4df89254540b6e

I tried to simplify it by adding the following helper function:

```
func native-color(user LumiColor col)->(var Color c)
    c := convert-to-native-color(copy col.r, copy col.g, copy col.b, copy col.a)
```

Upon updating the code and attempting to build it, I get the following error:

```
test.c: In function 'LUMI_user_main':
test.c:2396:29: error: invalid initializer
 2396 |         Color aux_Color_0 = 0;
      |                             ^
test.c:2403:29: error: invalid initializer
 2403 |         Color aux_Color_1 = 0;
      |                             ^
C compiler failed
```

Making the type an alias to `"struct Color"` does not help, outputting the following error:

```
$ ./build test.5.lm
test.c: In function 'LUMI_user_main':
test.c:2396:36: error: invalid initializer
 2396 |         struct Color aux_Color_0 = 0;
      |                                    ^
test.c:2403:36: error: invalid initializer
 2403 |         struct Color aux_Color_1 = 0;
      |                                    ^
C compiler failed
```

Is there any way to force Lumi to initialize this properly?

Alternatively, I tried binding to the native types for each color, but, since it's an initialized struct defined via a `#define` macro, Lumi wasn't happy with it.

**Comment by meircif** [comment]
This should work:
`native var Color light-gray "LIGHTGRAY"`

native struct support is truly incomplete in the current state of Lumi,
It is planned to add something like:
```
native struct Color "Color"
    var cdef.Uchar r "r"
    var cdef.Uchar g "g"
    var cdef.Uchar b "b"
    var cdef.Uchar a "a"
```
Then it will be easier.

**Comment by pluckyporcupine** [comment]
That worked, thanks!

Yeah, it looks like I can work around the missing features right now, as I did, but it does make passing Lumi structs based on a native type back to native code a bit more work than is ideal right now. I'll be looking out for the native struct update for sure!
