### ISSUE TITLE
How do I handle native functions that take no arguments and return nothing with the new C interop system?

### ISSUE THREAD

**Issue by pluckyporcupine** [meircif/lumi-lang#193]
So, before, I had, for example, this:

`native func close-window()->() "CloseWindow"`

Now, I have this...

`native func close-window() "CloseWindow"`

...and it's throwing this error...

`Code error in ../stdlib/os.5.lm[15] output arguments to native function`

However, I also have this on the previous line, which is not throwing an error:

`native func init-window(copy Int w, copy Int h, copy cdef.Pointer{cdef.Char} text) "InitWindow"`

The only difference is that `InitWindow` takes arguments.

As a side-note, I did try looking at the documentation and, while there is a `void*` analog, I didn't see a `void` analog. I assume, since it's not complaining that it doesn't know the type `init-window`, that the correct way to do this is to just omit the type, but I am unsure.

**Comment by meircif** [comment]
If you get:
`Code error in ../stdlib/os.5.lm[15] output arguments to native function`
you probably have the old version of `stdlib/os.5.lm`.

**Comment by pluckyporcupine** [comment]
Oh man, I derped. I was reading that as being my file. I completely glossed over it being `os.5.lm`. Sorry about that.
